# Generated by Django 3.1.4 on 2021-01-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blogfile',
            new_name='blog_file',
        ),
    ]
