# Generated by Django 3.1.4 on 2021-01-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20210117_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
