# Generated by Django 3.1.4 on 2021-02-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_post_date',
            new_name='post_date',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_title',
            new_name='title',
        ),
    ]
